import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from './StoreProvider'
import Header from "@/components/header";
import Futter from "@/components/futter"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="body">
          <Providers>
            <div className="HeaderDiv">
              <Header />
            </div>
            <div className="childrenDiv">
              {children}
            </div>
          </Providers>
        </div>
        <Futter />
      </body>
    </html>
  );
}
